### ISSUE TITLE
CSLA and WinForms

### ISSUE THREAD

**Issue by sanyo-ok** [MarimerLLC/cslacontrib#16]
Hello,

I was just looking for a "best pattern" method of binding WinForms controls like DevExpress XtraGrid to nHibernate collections. I did my own code using BindingSource, it works even with multilevel (master/detail) grids - any amount of levels.

I was aware there is better method to build applications using business level frameworks like CSLA.
It also has data binding features even for WinForms:
http://nugetmusthaves.com/Package/CSLA-WindowsForms

Then I read it is a good idea to use a ModelView pattern, especially if used together with XAML based GUI like WPF, UWP, etc. according to "Rockford Lhotka":
http://www.lhotka.net/weblog/WhyMVVM.aspx

There is an adapter for CaliburnMicro and specifically mod for WinForms:
https://github.com/MvvmFx/MvvmFx

Please suggest, is it a good idea to use following chain of components:
DevExpress WinForms XtragGrid -> MVVM->CSLA->nHibernate
?
I am reluctant to switch to WPF until MS unveils their plans to make WPF crossplatform at least on Linux.

For now DevExpress WinForms works fine on Linux + Wine and I do not have to spend time on learning WPF, look and feel of DevExpress WinForm is ok for me though my DXP license includes WPF too.

**Comment by tfreitasleal** [comment]
Hi,

The correct place to ask this question is on the [MvvmFx project](https://github.com/MvvmFx/MvvmFx), as you did. So I suggest we continue this topic on that project.
