### ISSUE TITLE
Caliburn Micro 3.0

### ISSUE THREAD

**Issue by ghost** [MarimerLLC/cslacontrib#17]
Hello, any plans to update ScreenWithModel and the CslaContrib-Caliburn.Micro.WPF NuGet Package to make it work with Caliburn Micro 3.0? The NuGet package still has a dependence to Calburn Micro 1,5.
Thanks

**Comment by tfreitasleal** [comment]
Hello Marcelo,

There is a version for Caliburn.Micro 2.0 but it isn't on NuGet (you have to download the project and build it). This is the first step to take but unfortunately time has limits. Back to your question, As far as I know, there are no contributors willing to port the ViewModel to Caliburn.Micro 3.0. Are you willing to do it?

**Comment by tfreitasleal** [comment]
Are there volunteers to execute this task?
