### ISSUE TITLE
Discontinue Visual WebGUI support

### ISSUE THREAD

**Issue by tfreitasleal** [MarimerLLC/cslacontrib#37]
VWG is no longer available.

**Comment by tfreitasleal** [comment]
Projects moved to a new branch.

**Comment by tanaponggithub** [comment]
I miss of a fast and efficient tool for tasks that don’t require frequent web structure/layou updates.

**Comment by tanaponggithub** [comment]
Is there any chance of coming back?

**Comment by rockfordlhotka** [comment]
Tiago has stopped contributing and responding. If you want to support this, please consider contributing.
